/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SucessoRouteImport } from './routes/sucesso'
import { Route as NegociacaoRouteImport } from './routes/negociacao'
import { Route as IndexRouteImport } from './routes/index'

const SucessoRoute = SucessoRouteImport.update({
  id: '/sucesso',
  path: '/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const NegociacaoRoute = NegociacaoRouteImport.update({
  id: '/negociacao',
  path: '/negociacao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/negociacao': typeof NegociacaoRoute
  '/sucesso': typeof SucessoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/negociacao': typeof NegociacaoRoute
  '/sucesso': typeof SucessoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/negociacao': typeof NegociacaoRoute
  '/sucesso': typeof SucessoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/negociacao' | '/sucesso'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/negociacao' | '/sucesso'
  id: '__root__' | '/' | '/negociacao' | '/sucesso'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NegociacaoRoute: typeof NegociacaoRoute
  SucessoRoute: typeof SucessoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sucesso': {
      id: '/sucesso'
      path: '/sucesso'
      fullPath: '/sucesso'
      preLoaderRoute: typeof SucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negociacao': {
      id: '/negociacao'
      path: '/negociacao'
      fullPath: '/negociacao'
      preLoaderRoute: typeof NegociacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NegociacaoRoute: NegociacaoRoute,
  SucessoRoute: SucessoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
